disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Oleksandr Ch."

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Oleksandr Ch."
  email = "mutantsan@gmail.com"
  image = "https://avatars.githubusercontent.com/u/55234934?v=4"
  imageQuality = 96
  headline = "Software Engineer"
  bio = "Open-source enthusiast, developer, and lifelong learner."
  links = [
    { email = "mailto:mutantsan@gmail.com" },
    { github = "https://github.com/mutantsan" },
    { linkedin = "https://www.linkedin.com/in/oleksandr-c-a0a63318a/" },
  ]
